webserver/Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webserver/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.index, name='idx'),
    path('get/', views.index_GET, name='idx_get'),
    path('post/', views.index_POST, name='idx_post'),
    path('post/search/', views.index_Search, name='idx_SR'),
    path('search/', views.index_Search, name='idx_SR'),
    path('tables/', views.index_Tables, name='idx_TB'),
    path('address/', views.index_Address, name='idx_AR'),
    path('main/number/', views.index_NumberMain, name='idx_NBM'),
    path('main/number/day/', views.index_NumberMain_D, name='idx_NBMD'),
    path('main/number/week/', views.index_NumberMain_W, name='idx_NBMW'),
    path('main/number/month/', views.index_NumberMain_A, name='idx_NBMA'),
    path('api/graph/', views.ElvtAPIVIEW_T.as_view(), name="idx_APIT"),
    path('api/graph/day/', views.ElvtAPIVIEW_D.as_view(), name="idx_APID"),
    path('api/graph/week/', views.ElvtAPIVIEW_W.as_view(), name="idx_APIW"),
    path('api/graph/month/', views.ElvtAPIVIEW_A.as_view(), name="idx_APIA"),
    path('graph/', views.index_GraphT, name='idx_GPT'),
    path('graph/day/', views.index_GraphD, name='idx_GPD'),
    path('graph/week/', views.index_GraphW, name='idx_GPW'),
    path('graph/month/', views.index_GraphA, name='idx_GPA'),
    path('graphic/', views.index_Graphic, name='idx_GRP'),
    path('blogMain/', views.blogMain, name='blogMain'),
    path('blogS/', views.blogS, name='blogS'),
]

webserver/poll/models.py
from django.db import models

# Create your models here.

webserver/poll/forms.py
from django import forms

class ElvtNumber(forms.Form):
    elvtNumber = forms.CharField(label="승강기 번호 ", required=False)

class ElvtAddress(forms.Form):
    elvtAddress = forms.CharField(label="승강기 주소/건물명", required=False)

class ElvtLogin(forms.Form):
    ID = forms.CharField(label="ID")
    password = forms.CharField(label="Password", widget=forms.PasswordInput())

class ElvtAddresList(forms.Form):
    address = forms.CharField()

webserver/poll/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from datetime import datetime, timedelta
from time import mktime, strptime
from .forms import *
import requests, json, math

class ElvtAPIVIEW_A(APIView): # 한달
	authentication_classes = []
	permission_classes = []

	def get(self, request):
		date_list = []
		acceleration_list = []
		altitude_list = []

		date_now = datetime.now()
		date_now = (date_now - timedelta(days=30))
		date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")
		date_now = datetime.strptime(date_now, "%Y-%m-%d %H:%M:%S").date()

		url = "http://210.119.145.22/data/"
		d = {"number": number, "date": date_now}
		res = requests.post(url, d)
		mybytes = res.text
		mybytes = json.loads(mybytes)

		for i in mybytes:
			utc_now = mktime(strptime(str(i['date']), '%Y-%m-%d %H:%M:%S')) * 1000
			date_list.append(i['date'])
			acceleration_list.append([utc_now, i['acceleration_z']])
			altitude_list.append([utc_now, i['current_altitude']])

		context = {
			'acceleration': acceleration_list,
			'altitude': altitude_list,
			'date': date_list
		}
		return Response(context)

class ElvtAPIVIEW_T(APIView):
	authentication_classes = []
	permission_classes = []

	def get(self, request):
		date_list = []
		acceleration_list = []
		altitude_list = []

		date_now = datetime.now()
		date_now = (date_now - timedelta(hours=1))
		date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")

		url = "http://210.119.145.22/data/"
		d = {"number": number, "date": date_now}
		res = requests.post(url, d)
		mybytes = res.text
		mybytes = json.loads(mybytes)

		for i in mybytes:	# 한시간
			utc_now = mktime(strptime(str(i['date']), '%Y-%m-%d %H:%M:%S')) * 1000
			date_list.append(i['date'])
			acceleration_list.append([utc_now, i['acceleration_z']])
			altitude_list.append([utc_now, i['current_altitude']])

		context = {
			'acceleration': acceleration_list,
			'altitude': altitude_list,
			'date': date_list
		}
		return Response(context)

class ElvtAPIVIEW_D(APIView):
	authentication_classes = []
	permission_classes = []

	def get(self, request):
		date_list = []
		acceleration_list = []
		altitude_list = []

		date_now = datetime.now()
		date_now = (date_now - timedelta(days=1))
		date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")
		date_now = datetime.strptime(date_now, "%Y-%m-%d %H:%M:%S").date()

		url = "http://210.119.145.22/data/"
		d = {"number": number, "date": date_now}
		res = requests.post(url, d)
		mybytes = res.text
		mybytes = json.loads(mybytes)

		for i in mybytes:	# 하루
			utc_now = mktime(strptime(str(i['date']), '%Y-%m-%d %H:%M:%S')) * 1000
			date_list.append(i['date'])
			acceleration_list.append([utc_now, i['acceleration_z']])
			altitude_list.append([utc_now, i['current_altitude']])

		context = {
			'acceleration': acceleration_list,
			'altitude': altitude_list,
			'date': date_list
		}
		return Response(context)

class ElvtAPIVIEW_W(APIView):
	authentication_classes = []
	permission_classes = []

	def get(self, request):
		date_list = []
		acceleration_list = []
		altitude_list = []

		date_now = datetime.now()
		date_now = (date_now - timedelta(days=7))
		date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")
		date_now = datetime.strptime(date_now, "%Y-%m-%d %H:%M:%S").date()

		url = "http://210.119.145.22/data/"
		d = {"number": number, "date": date_now}
		res = requests.post(url, d)
		mybytes = res.text
		mybytes = json.loads(mybytes)

		for i in mybytes:	# 일주일
			utc_now = mktime(strptime(str(i['date']), '%Y-%m-%d %H:%M:%S')) * 1000
			date_list.append(i['date'])
			acceleration_list.append([utc_now, i['acceleration_z']])
			altitude_list.append([utc_now, i['current_altitude']])

		context = {
			'acceleration': acceleration_list,
			'altitude': altitude_list,
			'date': date_list
		}
		return Response(context)

def index(request):
	url = "http://210.119.145.22/user/"
	if request.method == "POST":
		form = ElvtLogin(request.POST)
		if form.is_valid():
			my_id = form.cleaned_data['ID']
			password = form.cleaned_data['password']
			i = {
				'my_id': my_id,
				'password': password
			}
			res = requests.post(url, data=i)
			mybytes = res.text
			mybytes = json.loads(mybytes)

		if mybytes['msg'] == 'success':
			return HttpResponseRedirect('/poll/search/')
		else:
			return render(request, 'poll/index_Err.html')
	else:
		form = ElvtLogin()
	return render(request, 'poll/index_LG.html', {'form': form})

def index_GET(request):	# param_example : {"sensor":"test"}
	url = "http://210.119.145.22/data/"
	res = requests.get(url)
	mybytes = res.text
	context = {'mybytes': mybytes}
	return render(request, 'poll/index_GET.html', context)

def index_POST(request):
	url = "http://210.119.145.22/data/details/"
	d = { 'number' : '5057510'}
	res = requests.post(url, data=d)
	mybytes = res.text
	context = {'mybytes': mybytes }
	return render(request, 'poll/index_POST.html', context)

def index_Search(request):
	global number
	global address
	if request.method == "POST":
		form0 = ElvtNumber(request.POST)
		form1 = ElvtAddress(request.POST)
		if form0.is_valid():
			number = form0.cleaned_data['elvtNumber']
			if number:
				return HttpResponseRedirect('/poll/main/number/')
		if form1.is_valid():
			address = form1.cleaned_data['elvtAddress']
			if address:
				return HttpResponseRedirect('/poll/address/')
	else:
		form0 = ElvtNumber()
		form1 = ElvtAddress()
	return render(request, 'poll/index_SR.html', {'form0': form0, 'form1': form1})

def index_Tables(request):
	url = "http://210.119.145.22/data/details/"
	d = {'number': number}
	res = requests.post(url, data=d)
	mybytes = res.text
	mybytes = json.loads(mybytes)
	context = {'mybytes': mybytes}
	return render(request, 'poll/index_TB.html', context)

def index_Address(request):
	global number
	context = []

	url = "http://210.119.145.22/data/address/"
	d = {'address': address}
	res = requests.post(url, data=d)
	mybytes = res.text
	mybytes = json.loads(mybytes)

	for op in mybytes:
		context.append(op['address'])

	if request.method == "POST":
		result = request.POST.get('address', 'False')
		result = requests.post(url, {'address': result})
		result = result.text
		result = json.loads(result)

		for op in result:
			number = op['number']
		return HttpResponseRedirect('/poll/main/number/')
	else:
		form = ElvtAddresList()

	return render(request, 'poll/index_AR.html', {'context': context, 'form': form})

def index_GraphA(request):
	context = {}
	return render(request, 'poll/index_GPA.html', context)

def index_GraphT(request):
	context = {}
	return render(request, 'poll/index_GPT.html', context)

def index_GraphD(request):
	context = {}
	return render(request, 'poll/index_GPD.html', context)

def index_GraphW(request):
	context = {}
	return render(request, 'poll/index_GPW.html', context)

def index_Graphic(request):
	date_now = datetime.now()
	date_now = (date_now - timedelta(hours=1))
	date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")
	# date_now = datetime.strptime(date_now, "%Y-%m-%d %H:%M:%S").date()

	url = "http://210.119.145.22/data/"
	d = {"number": number, "date": date_now}
	res = requests.post(url, d)
	mybytes = res.text
	mybytes = json.loads(mybytes)
	latest = mybytes[-1]
	late = mybytes[-2]

	layer = ((float)(latest['current_altitude']) - (float)(latest['base_altitude']))/(float)(latest['height'])
	acceleration = ((int)(latest['acceleration_z']) - (int)(late['acceleration_z']))/10

	context = {
		"layer": math.floor(layer),
		"acceleration": acceleration
	}

	if latest['ir'] == 1:
		return render(request, 'poll/index_GRPT.html', context)
	else :
		return render(request, 'poll/index_GRPF.html', context)

def index_NumberMain(request):	# 한시간
	date_now = datetime.now()
	date_now = (date_now - timedelta(hours=1))
	date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")

	url = "http://210.119.145.22/data/"
	d = {"number": number, "date": date_now}
	res = requests.post(url, data=d)
	mybytes = res.text
	mybytes = json.loads(mybytes)

	latest = mybytes[-1]
	late = mybytes[-2]

	layer = ((float)(latest['current_altitude']) - (float)(latest['base_altitude']))/(float)(latest['height'])
	acceleration = ((int)(latest['acceleration_z']) - (int)(late['acceleration_z']))/10

	context = {
		"layer": math.floor(layer),
		"acceleration": acceleration
	}

	if latest['ir'] == 1:
		return render(request, 'poll/index_MNT.html', context)
	else :
		return render(request, 'poll/index_MNF.html', context)

def index_NumberMain_D(request):	# 하루
	date_now = datetime.now()
	date_now = (date_now - timedelta(hours=1))
	date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")

	url = "http://210.119.145.22/data/"
	d = {"number": number, "date": date_now}
	res = requests.post(url, data=d)
	mybytes = res.text
	mybytes = json.loads(mybytes)

	latest = mybytes[-1]
	late = mybytes[-2]

	layer = ((float)(latest['current_altitude']) - (float)(latest['base_altitude']))/(float)(latest['height'])
	acceleration = ((int)(latest['acceleration_z']) - (int)(late['acceleration_z']))/10

	context = {
		"layer": math.floor(layer),
		"acceleration": acceleration
	}

	if latest['ir'] == 1:
		return render(request, 'poll/index_MNTD.html', context)
	else :
		return render(request, 'poll/index_MNFD.html', context)

def index_NumberMain_W(request):	# 일주일
	date_now = datetime.now()
	date_now = (date_now - timedelta(hours=1))
	date_now = date_now.strftime("%Y-%m-%d %H:%M:%S")

	url = "http://210.119.145.22/data/"
	d = {"number": number, "date": date_now}
	res = requests.post(url, data=d)
	mybytes = res.text
	mybytes = json.loads(mybytes)

	latest = mybytes[-1]
	late = mybytes[-2]

	layer = ((float)(latest['current_altitude']) - (float)(latest['base_altitude']))/(float)(latest['height'])
	acceleration = ((int)(latest['acceleration_z']) - (int)(late['acceleration_z']))/10

	context = {
		"layer": math.floor(layer),
		"acceleration": acceleration
	}

	if latest['ir'] == 1:

webserver/templates/poll/Index_GRPT.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{{ acceleration }}m/min<br>
{{ layer }}<img src="/static/image/ir_True.GIF">
</body>
</html>

webserver/templates/poll/index_Err.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script>
        alert("아이디/비밀번호 에러")
        window.location.replace(/poll/);
    </script>
</head>
<body>

</body>
</html>

webserver/templates/poll/index_GPA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div id="container">

    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

    $.ajax({
        url: "{% url 'poll:idx_APIA' %}",
        dataType: 'json',
        success: function (context) {

            Highcharts.setOptions({
              global: {
                useUTC: false
              }
            });

            Highcharts.chart('container', {
                chart: {
                  height: 500
                },

                title: {
                 text: '가속도/고도 한달 그래프'
                },

                rangeSelector: {
                    buttons: [{
                        type: 'hour',
                        count: 1,
                        text: '1h'
                    }, {
                        type: 'day',
                        count: 1,
                        text: '1D'
                    }, {
                        type: 'all',
                        count: 1,
                        text: 'All'
                    }],
                  selected: 5,
                  inputEnabled: false
                },

                xAxis: {
                    type: 'datetime',
                    labels:{
                      formatter: function(){
                        return Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.value);
                      },
<!--                      step: 3-->
                    }
                },

                yAxis: {
                    title : " "
                },

                tooltip: {
                  xDateFormat: '%Y-%m-%d %H:%M:%S',
                  split: true
                },

                series: [{
                      name: '가속도',
                      data: context.acceleration,
                      color: 'rgba(0,200,0,.6)',
                      lineWidth: 2
                  },
                  {
                      name: '고도',
                      data: context.altitude,
                      lineWidth: 3
                }],

                 legend: {
                    enabled: true,
                    align: 'left',
                    verticalAlign: 'top',
                    floating: true,
                    x: 30,
                    y: 70
                 },

                responsive: {
                    rules: [{
                      condition: {
                        maxWidth: 600
                      },
                      chartOptions: {
                        chart: {
                          height: 300
                        },
                        navigator: {
                          enabled: false
                        }
                      }
                    }]
                }

            });
        }
    });
    </script>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1t" value="1t" id="1t" onclick="location.href='/poll/graph/'">1T</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1d" value="1d" id="1d" onclick="location.href='/poll/graph/day/'">1D</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1w" value="1w" id="1w" onclick="location.href='/poll/graph/week/'">1W</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1m" value="1m" id="1m" onclick="location.href='/poll/graph/month'">1M</button>
        </div>
    </div>
</body>
</html>

webserver/templates/poll/index_GPD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div id="container">

    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

    $.ajax({
        url: "{% url 'poll:idx_APID' %}",
        dataType: 'json',
        success: function (context) {

            Highcharts.setOptions({
              global: {
                useUTC: false
              }
            });

            Highcharts.chart('container', {
                chart: {
                  height: 500
                },

                title: {
                 text: '가속도/고도 하루 그래프'
                },

                rangeSelector: {
                    buttons: [{
                        type: 'hour',
                        count: 1,
                        text: '1h'
                    }, {
                        type: 'day',
                        count: 1,
                        text: '1D'
                    }, {
                        type: 'all',
                        count: 1,
                        text: 'All'
                    }],
                  selected: 5,
                  inputEnabled: false
                },

                xAxis: {
                    type: 'datetime',
                    labels:{
                      formatter: function(){
                        return Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.value);
                      },
<!--                      step: 3-->
                    }
                },

                yAxis: {
                    title : " "
                },

                tooltip: {
                  xDateFormat: '%Y-%m-%d %H:%M:%S',
                  split: true
                },

                series: [{
                      name: '가속도',
                      data: context.acceleration,
                      color: 'rgba(0,200,0,.6)',
                      lineWidth: 2
                  },
                  {
                      name: '고도',
                      data: context.altitude,
                      lineWidth: 3
                }],

                 legend: {
                    enabled: true,
                    align: 'left',
                    verticalAlign: 'top',
                    floating: true,
                    x: 30,
                    y: 70
                 },

                responsive: {
                    rules: [{
                      condition: {
                        maxWidth: 600
                      },
                      chartOptions: {
                        chart: {
                          height: 300
                        },
                        navigator: {
                          enabled: false
                        }
                      }
                    }]
                }

            });
        }
    });
    </script>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1t" value="1t" id="1t" onclick="location.href='/poll/graph/'">1T</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1d" value="1d" id="1d" onclick="location.href='/poll/graph/day/'">1D</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1w" value="1w" id="1w" onclick="location.href='/poll/graph/week/'">1W</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1m" value="1m" id="1m" onclick="location.href='/poll/graph/month'">1M</button>
        </div>
    </div>
</body>
</html>

webserver/templates/poll/index_GPT.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div id="container">

    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

    $.ajax({
        url: "{% url 'poll:idx_APIT' %}",
        dataType: 'json',
        success: function (context) {

            Highcharts.setOptions({
              global: {
                useUTC: false
              }
            });

            Highcharts.chart('container', {
                chart: {
                  height: 500
                },

                title: {
                 text: '가속도/고도 한시간 그래프'
                },

                rangeSelector: {
                    buttons: [{
                        type: 'hour',
                        count: 1,
                        text: '1h'
                    }, {
                        type: 'day',
                        count: 1,
                        text: '1D'
                    }, {
                        type: 'all',
                        count: 1,
                        text: 'All'
                    }],
                  selected: 5,
                  inputEnabled: false
                },

                xAxis: {
                    type: 'datetime',
                    labels:{
                      formatter: function(){
                        return Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.value);
                      },
<!--                      step: 3-->
                    }
                },

                yAxis: {
                    title : " "
                },

                tooltip: {
                  xDateFormat: '%Y-%m-%d %H:%M:%S',
                  split: true
                },

                series: [{
                      name: '가속도',
                      data: context.acceleration,
                      color: 'rgba(0,200,0,.6)',
                      lineWidth: 2
                  },
                  {
                      name: '고도',
                      data: context.altitude,
                      lineWidth: 3
                }],

                 legend: {
                    enabled: true,
                    align: 'left',
                    verticalAlign: 'top',
                    floating: true,
                    x: 30,
                    y: 70
                 },

                responsive: {
                    rules: [{
                      condition: {
                        maxWidth: 600
                      },
                      chartOptions: {
                        chart: {
                          height: 300
                        },
                        navigator: {
                          enabled: false
                        }
                      }
                    }]
                }

            });
        }
    });
    </script>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1t" value="1t" id="1t" onclick="location.href='/poll/graph/'">1T</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1d" value="1d" id="1d" onclick="location.href='/poll/graph/day/'">1D</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1w" value="1w" id="1w" onclick="location.href='/poll/graph/week/'">1W</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1m" value="1m" id="1m" onclick="location.href='/poll/graph/month'">1M</button>
        </div>
    </div>
</body>
</html>

webserver/templates/poll/index_GPW.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div id="container">

    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

    $.ajax({
        url: "{% url 'poll:idx_APIW' %}",
        dataType: 'json',
        success: function (context) {

            Highcharts.setOptions({
              global: {
                useUTC: false
              }
            });

            Highcharts.chart('container', {
                chart: {
                  height: 500
                },

                title: {
                 text: '가속도/고도 일주일 그래프'
                },

                rangeSelector: {
                    buttons: [{
                        type: 'hour',
                        count: 1,
                        text: '1h'
                    }, {
                        type: 'day',
                        count: 1,
                        text: '1D'
                    }, {
                        type: 'all',
                        count: 1,
                        text: 'All'
                    }],
                  selected: 5,
                  inputEnabled: false
                },

                xAxis: {
                    type: 'datetime',
                    labels:{
                      formatter: function(){
                        return Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.value);
                      },
<!--                      step: 3-->
                    }
                },

                yAxis: {
                    title : " "
                },

                tooltip: {
                  xDateFormat: '%Y-%m-%d %H:%M:%S',
                  split: true
                },

                series: [{
                      name: '가속도',
                      data: context.acceleration,
                      color: 'rgba(0,200,0,.6)',
                      lineWidth: 2
                  },
                  {
                      name: '고도',
                      data: context.altitude,
                      lineWidth: 3
                }],

                 legend: {
                    enabled: true,
                    align: 'left',
                    verticalAlign: 'top',
                    floating: true,
                    x: 30,
                    y: 70
                 },

                responsive: {
                    rules: [{
                      condition: {
                        maxWidth: 600
                      },
                      chartOptions: {
                        chart: {
                          height: 300
                        },
                        navigator: {
                          enabled: false
                        }
                      }
                    }]
                }

            });
        }
    });
    </script>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1t" value="1t" id="1t" onclick="location.href='/poll/graph/'">1T</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1d" value="1d" id="1d" onclick="location.href='/poll/graph/day/'">1D</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1w" value="1w" id="1w" onclick="location.href='/poll/graph/week/'">1W</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1m" value="1m" id="1m" onclick="location.href='/poll/graph/month'">1M</button>
        </div>
    </div>
</body>
</html>

webserver/templates/poll/index_MNF.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{{ acceleration }}m/min<br>
{{ layer }}<img src="/static/image/ir_False.GIF"  width="50" height="50">
    <div id="container">

    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

    $.ajax({
        url: "{% url 'poll:idx_APIT' %}",
        dataType: 'json',
        success: function (context) {

            Highcharts.setOptions({
              global: {
                useUTC: false
              }
            });

            Highcharts.chart('container', {
                chart: {
                  height: 500
                },

                title: {
                 text: '가속도/고도 한시간 그래프'
                },

                rangeSelector: {
                    buttons: [{
                        type: 'hour',
                        count: 1,
                        text: '1h'
                    }, {
                        type: 'day',
                        count: 1,
                        text: '1D'
                    }, {
                        type: 'all',
                        count: 1,
                        text: 'All'
                    }],
                  selected: 5,
                  inputEnabled: false
                },

                xAxis: {
                    type: 'datetime',
                    labels:{
                      formatter: function(){
                        return Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.value);
                      },
<!--                      step: 3-->
                    }
                },

                yAxis: {
                    title : " "
                },

                tooltip: {
                  xDateFormat: '%Y-%m-%d %H:%M:%S',
                  split: true
                },

                series: [{
                      name: '가속도',
                      data: context.acceleration,
                      color: 'rgba(0,200,0,.6)',
                      lineWidth: 2
                  },
                  {
                      name: '고도',
                      data: context.altitude,
                      lineWidth: 3
                }],

                 legend: {
                    enabled: true,
                    align: 'left',
                    verticalAlign: 'top',
                    floating: true,
                    x: 30,
                    y: 70
                 },

                responsive: {
                    rules: [{
                      condition: {
                        maxWidth: 600
                      },
                      chartOptions: {
                        chart: {
                          height: 300
                        },
                        navigator: {
                          enabled: false
                        }
                      }
                    }]
                }

            });
        }
    });
    </script>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1t" value="1t" id="1t" onclick="location.href='/poll/main/number/'">1T</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1d" value="1d" id="1d" onclick="location.href='/poll/main/number/day/'">1D</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1w" value="1w" id="1w" onclick="location.href='/poll/main/number/week/'">1W</button>
            <button type="button" class="btn btn_secondary btn-lg btn_block" name="1m" value="1m" id="1m" onclick="location.href='/poll/main/number/month/'">1M</button>
        </div>
    </div>
</body>
</html>